### ISSUE TITLE
Module does not work under Ruby 2.5

### ISSUE THREAD

**Issue by kansasSamurai** [voxpupuli/puppet-windows_env#62]
## Affected Puppet, Ruby, OS and module versions/distributions

- Puppet: 6.4.2
- Ruby: 2.5.3
- Distribution: (not sure what his means) 
- Module version: mod 'puppet-windows_env', '3.2.0'

## How to reproduce (e.g Puppet code you use)
Seemingly any use of the windows_env module; specific example is:
```
  windows_env { 'CBI_ENV':
    ensure    => present,
    variable  => 'CBI_ENV',
    value     => $domain,
    mergemode => insert,
  }
```

## What are you seeing
errors in the output log (see below)

## What behaviour did you expect instead
expect environment variable to be set/updated per standard windows_env functionality

## Output log
```
change from 'absent' to 'present' failed: Could not set 'present' on ensure: uninitialized constant Win32::Registry::KEY_WOW64_64KEY

Did you mean? KEY_WOW64_64KEY (file: /etc/puppetlabs/code/environments/dev/modules/imx_puppet/manifests/imx_apg_app.pp, line: 17)

Source:	/Stage[main]/Imx_puppet::Imx_apg_app/Windows_env[CBI_ENV]/ensureFile:	/etc/puppetlabs/code/environments/dev/modules/imx_puppet/manifests/imx_apg_app.ppLine:	17
```

## Any additional information you'd like to impart
This change in behavior seems consistent with information from the following blog.  We actually do have servers with ruby 2.4 where this module is correctly working; the issue appears to be isolated to servers with ruby 2.5

https://blog.bigbinary.com/2017/10/18/ruby-2.5-has-removed-top-level-constant-lookup.html

**Comment by gguillotte** [comment]
Root cause via https://github.com/liamjbennett/puppet-win_facts/issues/3#issuecomment-25477764, an issue in another windows module:

> Yeah, it appears both of these try to instantiate KEY_WOW64_64KEY, see line 18 in the fact here:
>
> https://github.com/liamjbennett/puppet-win_facts/blob/master/lib/facter/windows_productkey.rb
>
> and line 5 in the puppetlabs registry module:
>
> https://github.com/puppetlabs/puppetlabs-registry/blob/master/lib/puppet_x/puppetlabs/registry.rb

Resolution in liamjbennett/puppet-win_facts is to not declare the constant:

https://github.com/liamjbennett/puppet-win_facts/pull/12/files

**Comment by igalic** [comment]
so this module should reference the new version of win_facts

**Comment by bastelfreak** [comment]
Hi,
based on a discussion in https://groups.io/g/voxpupuli/message/449 we decided to archive this repository. I'm going to close all issues and PRs. If you're interested in maintaining the module, please respond to our mailinglist.
