### ISSUE TITLE
Unable to Remove Entire Variable

### ISSUE THREAD

**Issue by RFBennet** [voxpupuli/puppet-windows_env#73]
I'm testing out using version 4.0.1 of the module against Puppet 6.17.0 on a Windows 10 device (Version 1909 Build 18363.10.16), and am unable to completely remove an environment variable.

This successfully creates the variable:
```
    windows_env { 'VariableX':
      ensure    => present,
      mergemode => clobber,
      value     => 'some value here'
    }
```

However, this fails to remove the variable:
```
    windows_env { 'VariableX':
      ensure    => absent,
      mergemode => clobber
    }
```

I can see the 'VariableX' entry at HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Session Manager\Environment, and have restarted at different points in my testing. All with the same result. I can remove the Value of the variable, but not the entire variable itself (even though the ReadMe states the above command should remove the variable completely).

Is this a bug?

**Comment by Francommit** [comment]
Facing the same problem - can't completely remove variables.

**Comment by JCW-USDA** [comment]
Same here - clobber seems to only append, not overwrite

**Comment by bastelfreak** [comment]
Hi,
based on a discussion in https://groups.io/g/voxpupuli/message/449 we decided to archive this repository. I'm going to close all issues and PRs. If you're interested in maintaining the module, please respond to our mailinglist.
