### ISSUE TITLE
Type needs to be enclosed in single quotes to work.

### ISSUE THREAD

**Issue by bwarren18** [voxpupuli/puppet-windows_env#78]
Hello and thank you for this module.

As shown in the [examples](https://forge.puppet.com/modules/puppet/windows_env#examples) type is not enclosed in quotes: 
```puppet
windows_env { 'JAVA_HOME=%ProgramFiles%\Java\jdk1.6.0_02':
      type => REG_EXPAND_SZ,
    }
```

However this throws an error: Evaluation Error: Resource type not found: REG_EXPAND_SZ

Enclosing 'REG_EXPAND_SZ' in quotes works properly.
```puppet
windows_env { 'JAVA_HOME=%ProgramFiles%\Java\jdk1.6.0_02':
      type => 'REG_EXPAND_SZ',
    }
```

**Comment by kenyon** [comment]
Indeed, bare strings must start with lowercase letters: https://puppet.com/docs/puppet/6/lang_data_string.html#lang_data_string_bare_words
