### ISSUE TITLE
Puppet 7.x support

### ISSUE THREAD

**Issue by RFBennet** [voxpupuli/puppet-windows_env#84]
Version 4.0.1 (https://forge.puppet.com/modules/puppet/windows_env) does not appear to support Puppet 7.x (Puppet >= 5.5.8 < 7.0.0).

Will an updated version be released that will officially support it?

**Comment by bastelfreak** [comment]
Hi,
based on a discussion in https://groups.io/g/voxpupuli/message/449 we decided to archive this repository. I'm going to close all issues and PRs. If you're interested in maintaining the module, please respond to our mailinglist.
